# Generated by Django 4.2.3 on 2023-08-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailing_massage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(max_length=150, verbose_name='Статус попытки'),
        ),
    ]
