# Generated by Django 4.2.3 on 2023-08-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_remove_log_user_mailing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='ответ сервера'),
        ),
    ]
